# Generated by Django 4.1.6 on 2023-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_tutorrequest_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringuser',
            name='major',
            field=models.CharField(choices=[('AE', 'Aerospace Engineering'), ('AAS', 'African American and African Studies'), ('AMST', 'American Studies'), ('ANTH', 'Anthropology'), ('ARCY', 'Archaeology'), ('ARH', 'Architectural History'), ('ARCH', 'Architecture'), ('ASTR', 'Astronomy'), ('IDST', 'Bachelor of Interdisciplinary Studies'), ('HSM', 'Bachelor of Professional Studies in Health Sciences Management'), ('BIOL', 'Biology'), ('BME', 'Biomedical Engineering'), ('CHE', 'Chemical Engineering'), ('CHEM', 'Chemistry'), ('CE', 'Civil Engineering'), ('CLAS', 'Classics'), ('COGS', 'Cognitive Science'), ('COMM', 'Commerce'), ('', 'Comparative Literature'), ('CPE', 'Computer Engineering'), ('CS', 'Computer Science (B.A.)'), ('DANC', 'Dance'), ('DRAM', 'Drama'), ('ECED', 'Early Childhood Education (BSEd)'), ('EALC', 'East Asian Languages, Literatures and Culture'), ('ECON', 'Economics'), ('ELE', 'Electrical Engineering'), ('ELED', 'Elementary Education (BSEd)'), ('ES', 'Engineering Science'), ('ENGL', 'English'), ('EVCS', 'Environmental Sciences'), ('ETP', 'Environmental Thought and Practice'), ('FREN', 'French'), ('GERM', 'German'), ('GETR', 'German Studies'), ('HIST', 'History'), ('ARTH', 'History of Art'), ('HBIO', 'Human Biology'), ('JEST', 'Jewish Studies'), ('KINE', 'Kinesiology (BSEd)'), ('LAST', 'Latin American Studies'), ('LING', 'Linguistics'), ('MSE', 'Materials Science and Engineering'), ('MATH', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MDST', 'Media Studies'), ('MSP', 'Medieval Studies'), ('MESA', 'Middle Eastern and South Asian Languages and Cultures'), ('MUSI', 'Music'), ('NESC', 'Neuroscience'), ('NURS', 'Nursing'), ('PHIL', 'Philosophy'), ('PHYS', 'Physics'), ('PST', 'Political and Social Thought'), ('PPL', 'Political Philosophy, Policy, and Law'), ('PL', 'Politics'), ('PSYC', 'Psychology'), ('RELG', 'Religious Studies'), ('SLAV', 'Slavic Languages and Literatures'), ('SOC', 'Sociology'), ('SPAN', 'Spanish'), ('SPED', 'Special Education (BSEd)'), ('SCD', 'Speech Communication Disorders'), ('STAT', 'Statistics'), ('ARTS', 'Studio Art'), ('SYS', 'Systems Engineering'), ('PLAN', 'Urban and Environmental Planning'), ('WGS', 'Women, Gender & Sexuality'), ('YSI', 'Youth & Social Innovation (BSEd)')], max_length=4),
        ),
    ]
