# Generated by Django 4.1.6 on 2023-05-02 22:10

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_tutoringuser_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringuser',
            name='favorite_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='NA', max_length=100), default=home.models.TutoringUser.get_default, size=None),
        ),
        migrations.AddField(
            model_name='tutoringuser',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
