# Generated by Django 4.1.6 on 2023-05-03 02:17

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_alter_tutoringuser_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoringuser",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="NA", max_length=255),
                default=home.models.TutoringUser.get_default,
                size=None,
            ),
        ),
    ]
